version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - fasttech-network

  productsmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productsmanager-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DB_Products;User Id=sa;Password=Your_password123;TrustServerCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
    networks:
      - fasttech-network

volumes:
  sqlserverdata:

networks:
  fasttech-network:
