version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - fasttech-network

  productsmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productsmanager-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DbProduct=Server=sqlserver;Database=DB_Products;User Id=sa;Password=Your_password123;TrustServerCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - fasttech-network
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"   
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - fasttech-network    

volumes:
  sqlserverdata:

networks:
  fasttech-network:
